<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Users Export - {{ date('Y-m-d') }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #4CAF50; color: white; font-weight: bold; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        h1 { text-align: center; color: #333; }
        .badge { padding: 3px 8px; border-radius: 3px; color: white; }
        .badge-success { background-color: #28a745; }
        .badge-danger { background-color: #dc3545; }
        .badge-warning { background-color: #ffc107; color: black; }
    </style>
</head>
<body>
    <h1>All Users Export Report</h1>
    <p style="text-align: center; color: #666;">Generated on: {{ date('d-m-Y H:i:s') }}</p>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Contact</th>
                <th>Email</th>
                <th>DOB</th>
                <th>Gender</th>
                <th>Aadhaar</th>
                <th>PAN</th>
                <th>City</th>
                <th>State</th>
                <th>Verified</th>
                <th>Completed</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name ?? 'N/A' }}</td>
                <td>{{ $user->contact_number }}</td>
                <td>{{ $user->email ?? 'N/A' }}</td>
                <td>{{ $user->dob ?? 'N/A' }}</td>
                <td>{{ ucfirst($user->gender ?? 'N/A') }}</td>
                <td>{{ $user->aadhar_number ?? 'N/A' }}</td>
                <td>{{ $user->pan_number ?? 'N/A' }}</td>
                <td>{{ $user->city ?? 'N/A' }}</td>
                <td>{{ $user->state ?? 'N/A' }}</td>
                <td>{{ $user->is_verified ? 'Yes' : 'No' }}</td>
                <td>{{ $user->is_completed ? 'Yes' : 'No' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <p style="margin-top: 30px; text-align: center; color: #666; font-size: 9px;">
        Total Users: {{ count($users) }} | Generated by DigiTransway System
    </p>
</body>
</html>
